services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  locust:
    image: locustio/locust:2.20.0
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/locust/locustfile.py  # Critical path change
    command: 
      - "--locustfile=/locust/locustfile.py"
      - "--host=http://web:5000"  # Uses Docker's internal networking
    depends_on:
      - web
