version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - FLASK_ENV=production  # Use "production" for Render
    restart: unless-stopped

  locust:
    image: locustio/locust:2.20.0  # Pin version for stability
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py  # Directly mount the file
    command: 
      - "--headless"  # Disable UI for Render (or remove for local testing)
      - "--host=http://web:5000"
      - "--users=100"
      - "--spawn-rate=10"
      - "--run-time=1m"
    depends_on:
      - web
    environment:
      - LOCUST_WEB_AUTH=admin:password  # Optional auth
