services:
  - type: web
    name: flood-prediction-app
    runtime: python
    buildCommand: pip install -r src/requirements.txt
    startCommand: gunicorn src.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
